---
title: "Cov2Comparator"
author: "Kuai Yu"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cov2Comparator}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction
Cov2Comparator is a package that analyzes SARS covid-2 genome across different 
geographic regions. It allows easy retrieval of SARS COV-2 genome 
. It can perform multiple sequence alignments and 
phylogenetic tree. Plot of multiple sequence alignments and 
phylogenetic tree can be generated for interpretation. This document gives a 
tour of Cov2Comparator package.

see `help(package = "Cov2Comparator")` for more information and 
references provided by `citation("Cov2Comparator")`

To download **Cov2Comparator**, use the following commands:

```r
require("devtools")
devtools::install_github("quick2063706271/Cov2Comparator", build_vignettes = TRUE)
library("Cov2Comparator")
```

To list all functions available in this package:

```r
ls("package:Cov2Comparator")
```

To list dataset in this package:

``` r
data(package = "Cov2Comparator")
```

## Components
There are 7 functions in this package

### Loading and retrieving sequence from NCBI 
There are three ways to load and retrieve sequence. 
__*getSequenceByRegion*__ allows user to retrieve a SARS-COV2 genome by 
inputting a region which user desired. Current supports input from 
(Canada, Italy, Wuhan, USA, Kenya, Bahrain, Germany, Pakistan, Britain, 
Thailand)

Here is an example.
```r
# Please make sure you are connected to the internet
wuhanSeq <- getSequenceByRegion("Wuhan")
print(wuhanSeq)
```
```
# DNAStringSet object of length 1:
#    width seq                                                                                                                            names               
# [1] 29903 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGT...
GATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA NC_045512.2 Wuhan
```

__*getSequencesByRegions*__ allows user to retrieve a SARS-COV2 genome by 
inputting multiple regions which user desired. Current supports input from 
(Canada, Italy, Wuhan, USA, Kenya, Bahrain, Germany, Pakistan, Britain, 
Thailand)

```r
# Please make sure you are connected to the internet
regions <- c("Wuhan", "Italy", "USA")
seqs <- getSequencesByRegions(regions)
print(seqs)
```

The last way to add is using __*readGenome*__. This function allows user to input fasta file as input, user can also include a nameToRegion file, which contains one to one correspondence of accessionID and region.
```r
fastaPath1 <- system.file("extdata", "MN985325.1.fasta", package="Cov2Comparator")
nameToRegionsFile <- system.file("extdata", "nameToCountry.txt", package="Cov2Comparator")
fasta1 <- readGenome(fastaPath1, nameToRegionsFile)
fasta1
```

```
# DNAStringSet object of length 1:
#     width seq                                                                                                                  names               
# [1] 29882 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...AGTGCT
ATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAA MN985325.1 USA
```

User do not to provide nameToRegion file. In that case, users are recommanded to
modify the name by themselves

```r
fastaPath1 <- system.file("extdata", "MN985325.1.fasta", package="Cov2Comparator")
nameToRegionsFile <- system.file("extdata", "nameToCountry.txt", package="Cov2Comparator")
fasta1 <- readGenome(fastaPath1)
print(fasta1)
# After modifying name
cat("\nAfter modifying name\n\n")
names(fasta1) <- c("MN985325.1 USA")
print(fasta1)
```

```
# DNAStringSet object of length 1:
#     width seq                                                                                                                  names               
# [1] 29882 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...
AGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAA MN985325.1 Severe...
#
# After modifying name
#
# DNAStringSet object of length 1:
#     width seq                                                                                                                  names               
# [1] 29882 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...AGTGC
TATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAA MN985325.1 USA
```

## multiple sequence alignment
After loading the data, we can perform a multiple sequence alignment using 
__*multiplSeqAlign*__. This functions is derived from __*msa::msa*__ 
```r
# It will takes several minutes
seqs
align <- multipleSeqAlign(seqs, algorithm = 'ClustalW')
align
```
```
# DNAStringSet object of length 3:
#     width seq                                                                                                                  names               
# [1] 29903 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...TAATA
GCTTCTTAGGAGAATGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA NC_045512.2 Wuhan
# [2] 29867 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...AAAA
TTAATTTTAGTAGTGCTATCCCCATGTGATTTTAATAGCTTCTTAGGAGAAT MT066156.1 Italy
# [3] 29882 ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA...AGTGC
TATCCCCATGTGATTTTAATAGCTTCTTAGGAGAATGACAAAAAAAAAAAA MN985325.1 USA
# use default substitution matrix
# CLUSTAL 2.1  
# 
# Call:
#    msa::msaClustalW(sequences)
#
# MsaDNAMultipleAlignment with 3 rows and 29903 columns
#     aln                                                                                                                       names
# [1] ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATC...TTTTAATAG
CTTCTTAGGAGAATGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA NC_045512.2 Wuhan
# [2] ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATC...TTTTAATAG
CTTCTTAGGAGAATGACAAAAAAAAAAAA--------------------- MN985325.1 USA
# [3] ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATC...TTTTAATAG
CTTCTTAGGAGAAT------------------------------------ MT066156.1 Italy
# Con ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATC...TTTTAATAG
CTTCTTAGGAGAATGACAAAAAAAAAAAA--------------------- Consensus 
```
You can also use "Muscle" as algorithm to perform the alignment
```r
# It will takes several minutes
align <- multipleSeqAlign(seqs, algorithm = 'muSCLE') # case does not matter
align
```

We can plot the alignment using __*plotAlignment*__

```r
p <- plotAlignment(alignment = align, refid = 'NC_045512.2 Wuhan', startIdx = 29820, endIdx = 29902)
p
```

After that, multiple sequence alignment can be used to generate phylogenetic 
tree using __*createTree*__

## Phylogenetic tree
```r
tree <- createTree(align)
```

Tree can be ploted using __*plotTree*__

```r
plotTree(tree,
         name = "demo Alignment",
         showRegionName = TRUE)
```
Tree can be ploted using __*plotTree*__ without region names followed
```r
plotTree(tree,
         name = "demo Alignment",
         showRegionName = FALSE)
```









## Reference
R Core Team (2021). R: A language and environment for statistical computing. 
R Foundation for Statistical Computing, Vienna, Austria. URL
  https://www.R-project.org/.

Charif, D. and Lobry, J.R. (2007). SeqinR 1.0-2: a contributed package to the R
project for statistical computing devoted to biological sequences retrieval
and analysis. Structural approaches to sequence evolution: Molecules, networks,
populations, series Biological and Medical Physics, Biomedical Engineering,
207-232. Springer Verlag, New York.

Ulrich Bodenhofer, Enrico Bonatesta, Christoph Horejs-Kainrath, & Sepp 
Hochreiter (2015). msa: an R package for multiple sequence alignment. 
Bioinformatics, 31(24), 3997–3999.

Paradis E. & Schliep K. (2019). ape 5.0: an environment for modern
phylogenetics and evolutionary analyses in R. Bioinformatics 35: 526-528.

Raivo Kolde (2019). pheatmap: Pretty Heatmaps. R package version 1.0.12.
https://CRAN.R-project.org/package=pheatmap

BioRender. (2020). Image created by Silva, A. Retrieved November 16, 2021, 
from https://app.biorender.com/



